[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1

remappings = [
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/",
    "soledge/=lib/wei-names/lib/soledge/src/",
    "@wei-names/=lib/wei-names/src/"
]

[profile.default.fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"

[rpc_endpoints]
megaeth = "https://rpc.megaeth.com"
megaeth_testnet = "https://carrot.megaeth.com/rpc"
